//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Manager.Core.Classes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("School_Manager.Core.Classes.ValidatorMessage", typeof(ValidatorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد فعال برای این فرزند در بازه مشخص شده وجود دارد..
        /// </summary>
        internal static string DuplicatedContract {
            get {
                return ResourceManager.GetString("DuplicatedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر وارد شده قبلاً برای راننده ثبت شده است..
        /// </summary>
        internal static string DuplicatedDriver {
            get {
                return ResourceManager.GetString("DuplicatedDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل تکراری است..
        /// </summary>
        internal static string DuplicatedMobile {
            get {
                return ResourceManager.GetString("DuplicatedMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر وارد شده قبلاً برای والدین ثبت شده است..
        /// </summary>
        internal static string DuplicatedParent {
            get {
                return ResourceManager.GetString("DuplicatedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است..
        /// </summary>
        internal static string DuplicatedUserName {
            get {
                return ResourceManager.GetString("DuplicatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی باید بیشتر از صفر باشد..
        /// </summary>
        internal static string IdGreatorThanZero {
            get {
                return ResourceManager.GetString("IdGreatorThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی نباید بیشتر از {0} کاراکتر باشد..
        /// </summary>
        internal static string LastNameLimitCharacter {
            get {
                return ResourceManager.GetString("LastNameLimitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل نباید بیشتر از {0} کاراکتر باشد..
        /// </summary>
        internal static string MobileLimitCharacter {
            get {
                return ResourceManager.GetString("MobileLimitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نباید بیشتر از {0} کاراکتر باشد..
        /// </summary>
        internal static string NameLimitCharacter {
            get {
                return ResourceManager.GetString("NameLimitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نباید بیشتر از {0} کاراکتر باشد..
        /// </summary>
        internal static string NationalLimitCharacter {
            get {
                return ResourceManager.GetString("NationalLimitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ باید بیشتر از صفر باشد..
        /// </summary>
        internal static string PriceGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری الزامی است..
        /// </summary>
        internal static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی الزامی است..
        /// </summary>
        internal static string RequireLastName {
            get {
                return ResourceManager.GetString("RequireLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدیر الزامی است..
        /// </summary>
        internal static string RequireManagerName {
            get {
                return ResourceManager.GetString("RequireManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل الزامی است.
        /// </summary>
        internal static string RequireMobile {
            get {
                return ResourceManager.GetString("RequireMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام  الزامی است..
        /// </summary>
        internal static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی الزامی است..
        /// </summary>
        internal static string RequireNationalCode {
            get {
                return ResourceManager.GetString("RequireNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری نباید بیشتر از {0} کاراکتر باشد.
        /// </summary>
        internal static string UserNameLimitCharacter {
            get {
                return ResourceManager.GetString("UserNameLimitCharacter", resourceCulture);
            }
        }
    }
}
