// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Manager.Data.Context;

#nullable disable

namespace School_Manager.Data.Migrations
{
    [DbContext(typeof(SchMSDBContext))]
    partial class SchMSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.App.Trail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffectedColumns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditTrials", "dbo");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام خانوادگی");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("کلمه عبور");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام کاربری");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasComment("مبلغ");

                    b.Property<long>("ServiceContractRef")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceContractRef");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("ChrPlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColorCode")
                        .HasColumnType("int");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("DriverRef")
                        .HasColumnType("bigint");

                    b.Property<int>("FirstIntPlateNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام ماشین");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SecondIntPlateNumber")
                        .HasColumnType("int");

                    b.Property<int>("ThirdIntPlateNumber")
                        .HasColumnType("int");

                    b.Property<int>("carType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverRef");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Cheque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("CheckOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckSayadNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasComment("شناسه صیاد");

                    b.Property<string>("CheckSerial")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasComment("سریال چک");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Cheques", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Child", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام خانوادگی");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasComment("کد ملی");

                    b.Property<long>("ParentRef")
                        .HasColumnType("bigint");

                    b.Property<long?>("SchoolRef")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentRef");

                    b.HasIndex("SchoolRef");

                    b.ToTable("Children", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankRef")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام پدر");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام خانوادگی");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام");

                    b.Property<string>("NationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasComment("کد ملی");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserRef")
                        .HasColumnType("int");

                    b.Property<int>("Warnning")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRef");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverChild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChildRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("DriverRef")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildRef");

                    b.HasIndex("DriverRef");

                    b.ToTable("DriverChildren", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("DriverRef")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignatureImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverRef");

                    b.ToTable("DriverContracts", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverContractCheque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChequeRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("DriverContractRef")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverContractRef");

                    b.ToTable("DriverContractCheque", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.LocationData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<long?>("LocationPairRef")
                        .HasColumnType("bigint");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LocationPairRef");

                    b.ToTable("LocationData", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.LocationPair", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChildRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickTime1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickTime2")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildRef");

                    b.ToTable("LocationPair", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Lookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نوع");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasComment("مقدار");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("Lookup", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Parent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام خانوادگی");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasComment("کد ملی");

                    b.Property<int>("UserRef")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRef");

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Pay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BecomingTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Pays", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.PayBill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BillRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("PayRef")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillRef");

                    b.HasIndex("PayRef");

                    b.ToTable("PayBills", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryRef")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasComment("توضیحات");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MajorUnitRef")
                        .HasColumnType("int")
                        .HasComment("واحد اصلی");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کد کالا");

                    b.Property<int>("MaterialNature")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasComment("نام کالا");

                    b.Property<int?>("SecondaryUnitRef")
                        .HasColumnType("int")
                        .HasComment("واحد فرعی");

                    b.Property<int?>("SupplierRef")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalSpecification")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasComment("مشخصه فنی");

                    b.Property<double?>("UnitConversion")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RawMaterials", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام مدیر مدرسه");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نام مدرسه");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.ServiceContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChildRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("MonthPrice")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("SignatureImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChildRef");

                    b.ToTable("ServiceContracts", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.ServiceContractCheque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChequeRef")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("ServiceContractRef")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceContractRef");

                    b.ToTable("ServiceContractCheque", (string)null);
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Bill", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.ServiceContract", "ServiceContractNavigation")
                        .WithMany("BillNavigation")
                        .HasForeignKey("ServiceContractRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceContractNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Car", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Driver", "DriverNavigation")
                        .WithMany("Cars")
                        .HasForeignKey("DriverRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DriverNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Child", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Parent", "ParentNavigation")
                        .WithMany("Children")
                        .HasForeignKey("ParentRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.School", "SchoolNavigation")
                        .WithMany("Childs")
                        .HasForeignKey("SchoolRef")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentNavigation");

                    b.Navigation("SchoolNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Driver", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Identity.User", "UserNavigation")
                        .WithMany("Drivers")
                        .HasForeignKey("UserRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverChild", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Child", "ChildNavigation")
                        .WithMany("DriverChilds")
                        .HasForeignKey("ChildRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Driver", "DriverNavigation")
                        .WithMany("Passanger")
                        .HasForeignKey("DriverRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildNavigation");

                    b.Navigation("DriverNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverContract", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Driver", "DriverNavigation")
                        .WithMany("DriverContracts")
                        .HasForeignKey("DriverRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DriverNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverContractCheque", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Cheque", "ChequeNavigation")
                        .WithMany("DriverContractCheques")
                        .HasForeignKey("DriverContractRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.DriverContract", "DriverContractNavigation")
                        .WithMany("DriverContractCheques")
                        .HasForeignKey("DriverContractRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChequeNavigation");

                    b.Navigation("DriverContractNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.LocationData", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.LocationPair", "LocationPairNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("LocationPairRef")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocationPairNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.LocationPair", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Child", "ChildNavigation")
                        .WithMany("LocationPairs")
                        .HasForeignKey("ChildRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Parent", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Identity.User", "UserNavigation")
                        .WithMany("Parents")
                        .HasForeignKey("UserRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.PayBill", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Bill", "BillNavigation")
                        .WithMany("PayBills")
                        .HasForeignKey("BillRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Pay", "PayNavigation")
                        .WithMany("PayBills")
                        .HasForeignKey("PayRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillNavigation");

                    b.Navigation("PayNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.ServiceContract", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Child", "ChildNavigation")
                        .WithMany("ServiceContracts")
                        .HasForeignKey("ChildRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.ServiceContractCheque", b =>
                {
                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.Cheque", "ChequeNavigation")
                        .WithMany("ServiceContractCheques")
                        .HasForeignKey("ServiceContractRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School_Manager.Domain.Entities.Catalog.Operation.ServiceContract", "ServiceContractNavigation")
                        .WithMany("ServiceContractCheques")
                        .HasForeignKey("ServiceContractRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChequeNavigation");

                    b.Navigation("ServiceContractNavigation");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Identity.User", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Bill", b =>
                {
                    b.Navigation("PayBills");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Cheque", b =>
                {
                    b.Navigation("DriverContractCheques");

                    b.Navigation("ServiceContractCheques");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Child", b =>
                {
                    b.Navigation("DriverChilds");

                    b.Navigation("LocationPairs");

                    b.Navigation("ServiceContracts");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Driver", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("DriverContracts");

                    b.Navigation("Passanger");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.DriverContract", b =>
                {
                    b.Navigation("DriverContractCheques");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.LocationPair", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.Pay", b =>
                {
                    b.Navigation("PayBills");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.School", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("School_Manager.Domain.Entities.Catalog.Operation.ServiceContract", b =>
                {
                    b.Navigation("BillNavigation");

                    b.Navigation("ServiceContractCheques");
                });
#pragma warning restore 612, 618
        }
    }
}
